project:
  type: website
  output-dir: docs

website:
  title: "brycezilla"
  favicon: image0.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

